@startuml
Repository <|-- CrudRepository
CrudRepository <|-- PagingAndSortingRepository
PagingAndSortingRepository <|-- JpaRepository

class CrudRepository {
    findOne()
    findAll()
    delete()
    Exists()
    save()
}

class PagingAndSortingRepository {
    findAll(Sort sort)
    operation(Pageable pageable)
}

class JpaRepository {
    flush()
    saveAndFlush()
    deleteInBatch()
    getOne()
}
@enduml